workflows:
  unity-android-build:
    name: Unity Android Build
    max_build_duration: 120  # Limit czasu kompilacji (minuty)
    instance_type: mac_mini_m1  # Apple Mac Mini M1

    environment:
      vars:
        UNITY_VERSION: 2021.3.11f1  # Upewnij się, że to właściwa wersja Unity
      groups:
        - unity_credentials  # Klucz licencyjny Unity (dodamy w Codemagic)

    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "main"
          include: true
          source: true

    scripts:
      - name: Install dependencies
        script: |
          brew update
          brew install wget unzip

      - name: Install Unity
        script: |
          UNITY_DOWNLOAD_URL="https://download.unity3d.com/download_unity/2e8f6c65e5c9/MacEditorInstaller/Unity.pkg"
          wget -q $UNITY_DOWNLOAD_URL -O Unity.pkg
          sudo installer -pkg Unity.pkg -target /
          rm Unity.pkg

      - name: Activate Unity License
        script: |
          /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity \
            -quit -batchmode -nographics \
            -serial $UNITY_SERIAL -username $UNITY_EMAIL -password $UNITY_PASSWORD

      - name: Build APK
        script: |
          /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity \
            -quit -batchmode -nographics -projectPath . \
            -executeMethod BuildScript.PerformBuild \
            -buildTarget Android \
            -logFile unity_build.log

    artifacts:
      - build/*.apk  # Ścieżka do pliku APK


